[features]
seeds = false
skip-lint = false
[programs.devnet]
plus_program = "HBoWC3fVTep7FWfe1dFr1cWxiV3nQzStLwkgdnLjZymk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
